//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_REST
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class content_orders
    {
        public int id_content_order { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_dish { get; set; }
        public int count_dish { get; set; }
    
        public virtual list_of_dishes list_of_dishes { get; set; }
        public virtual orders orders { get; set; }




        //-------------------------------------------------------------------------------------------------------------------------------------------------------------------




        SmartRestaurantEntities db = new SmartRestaurantEntities();
        public static Dictionary<string, int> list = new Dictionary<string, int>();
        public void ListDihInOrder(int id_dish, int count)
        {
            if (count != 0)
            {
                var content = new content_orders();

                int MaxId;

                if (db.content_orders.Count() != 0)
                {
                    MaxId = int.Parse(db.content_orders.Max(p => p.id_content_order).ToString()) + 1;
                }
                else { if (orders.ListDishesinOrd.Count() != 0) { MaxId = orders.ListDishesinOrd.Max(p => p.id_content_order) + 1; } else MaxId = 1; }
                content.id_content_order = MaxId;
                content.id_dish = id_dish;
                content.count_dish = count;
                orders.ListDishesinOrd.Add(content);
            }
        }

    }
}
