//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_REST
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu()
        {
            this.list_of_dishes = new HashSet<list_of_dishes>();
        }

        public int id_selection { get; set; }
        public string name_selection { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_of_dishes> list_of_dishes { get; set; }


        static SREntities db = new SREntities();
        public static List<menu> ComboSel()   //вывод всех разделов
        {
            var selectPos = (from m in db.menu select m).ToList();
            return selectPos;
        }
        public static dynamic SelectSel(object posit)   //поиск  по названию выбранной раздела
        {
            var pos = db.menu.First(p => p.name_selection == posit.ToString());
            return pos.id_selection;
        }
    }
}
