//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_REST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartRestaurantEntities : DbContext
    {
        public SmartRestaurantEntities()
            : base("name=SmartRestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<content_orders> content_orders { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<list_of_dishes> list_of_dishes { get; set; }
        public virtual DbSet<list_of_table> list_of_table { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<positions> positions { get; set; }
        public virtual DbSet<stocks> stocks { get; set; }
    }
}
